version: 2.1
orbs:
  win: circleci/windows@2.4.0
jobs:
   build-medium-amd64:
    machine:
      image: ubuntu-2004:202101-01
   
    working_directory: ~/dash
    steps:      
      - checkout
      - run:
          name: ️️requirements
          command: |
             uname -m 
             sudo apt update
             sudo apt install python3
             sudo apt-get install python3-pip
             pip3 install tox
             pip3 install -r test-requirements.txt
             cd src
             python3 -m unittest test_typing_extensions.py
             
   build-medium-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/dash
    steps:
      
      - checkout
      - run:
          name: ️️requirements
          command: |
             uname -m 
             sudo apt update
             sudo apt install python3
             sudo apt-get install python3-pip
             pip3 install tox
             pip3 install -r test-requirements.txt
             cd src
             python3 -m unittest test_typing_extensions.py
             
   lint-unit-39: &lint-unit
    working_directory: ~/dash
    docker:
      - image: circleci/python:3.9.2-buster-node-browsers
    steps:
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
            uname -m  
            sudo apt update
            sudo apt install python3
            sudo apt-get install python3-pip
            pip3 install tox
            pip3 install -r test-requirements.txt
            flake8
            flake8 --config=.flake8-tests src/test_typing_extensions.py
       
workflows:
  version: 2
  python3.9:
    jobs:
     
      - lint-unit-39
      - build-medium-amd64
      - build-medium-arm64
